"""GATE: byte-parity with the reference implementation.

Fixtures under ``tests/fixtures/parity/`` are generated by the reference
implementation's fixture emitter (see CONTRIBUTING). For each canonical corpus,
every field of every slice — geometry in both coordinate systems, the marker,
and the descendant-marker list *in order* — must match exactly. Markers agree
if and only if UTF-8 handling, grid math, and hashing all agree; this is the
cross-language anchor. (Point UUIDs are deliberately excluded: this project
derives IDs under its own namespace.)
"""

import json
from pathlib import Path

import pytest

from phoropter import GridSpec, multi_view_slice

pytestmark = pytest.mark.gate

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "parity"

EXPECTED_FIXTURES = {"ascii-x1024", "cjk-1024", "emoji-1024", "multiscript-1024"}


def load_fixtures() -> list[dict]:
    files = sorted(FIXTURE_DIR.glob("*.json"))
    return [json.loads(f.read_text(encoding="utf-8")) for f in files]


def test_all_expected_fixtures_present() -> None:
    names = {f["name"] for f in load_fixtures()}
    missing = EXPECTED_FIXTURES - names
    assert not missing, (
        f"parity fixtures missing: {sorted(missing)} — regenerate from the reference implementation"
    )


def test_fixtures_carry_generation_provenance() -> None:
    for fixture in load_fixtures():
        provenance = fixture.get("generated_from", {})
        assert provenance.get("git_sha"), (
            f"fixture {fixture['name']} lacks generated_from.git_sha — "
            "regenerate with the current emitter (see CONTRIBUTING)"
        )


@pytest.mark.parametrize("fixture", load_fixtures(), ids=lambda f: f["name"])
def test_slice_by_slice_parity(fixture: dict) -> None:
    grid = GridSpec(tuple(fixture["grid_sizes"]))
    text = fixture["text"]
    doc = multi_view_slice("doc", text, grid)

    assert doc.codepoint_length == fixture["document"]["codepoint_length"]
    assert doc.byte_length == fixture["document"]["byte_length"]

    theirs = {(s["size"], s["codepoint_offset"]): s for s in fixture["slices"]}
    ours = {(s.size, s.codepoint_offset): s for s in doc.slices}
    assert set(ours) == set(theirs), "slice coordinate sets differ"

    for key, ref in theirs.items():
        mine = ours[key]
        assert mine.codepoint_length == ref["codepoint_length"], key
        assert mine.byte_offset == ref["byte_offset"], key
        assert mine.byte_length == ref["byte_length"], key
        assert mine.text == ref["text"], key
        assert mine.own_marker == ref["own_marker"], key
        assert list(mine.descendant_markers) == ref["descendant_markers"], (
            f"descendant markers (or their order) differ at {key}"
        )
