# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-11T02:43:37+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class Status(StrEnum):
    ok = 'ok'


class Liveness(BaseModel):
    """
    Liveness result.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status


class Status1(StrEnum):
    """
    Overall readiness.
    """

    ok = 'ok'
    degraded = 'degraded'


class Readiness(BaseModel):
    """
    Readiness detail across dependencies.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: Annotated[Status1, Field(description='Overall readiness.')]
    store: Annotated[bool, Field(description='Whether the vector store is reachable.')]
    embedder: Annotated[bool, Field(description='Whether the embedder is reachable.')]
    detail: Annotated[
        str | None, Field(description='Human-readable explanation when degraded.')
    ] = None


class Info(BaseModel):
    """
    Build and registry metadata.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    version: str
    store: Annotated[str, Field(description='The configured store kind.')]
    embedder: Annotated[
        str, Field(description='The configured embedder pin (`provider:model`).')
    ]
    stores_available: Annotated[
        list[str],
        Field(description='Store adapter names registered under the plugin group.'),
    ]
    embedders_available: Annotated[
        list[str] | None,
        Field(description='Embedder provider names registered under the plugin group.'),
    ] = None


class GridSpec(BaseModel):
    """
    A validated ladder of slice sizes (code points), ascending, each dividing the next.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    sizes: Annotated[list[int], Field(min_length=1)]


class CreateCorpusRequest(BaseModel):
    """
    Corpus creation. Omitted fields fall back to server defaults.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Annotated[
        str,
        Field(
            description='Corpus name; unique within the store.',
            max_length=128,
            min_length=1,
        ),
    ]
    grid_sizes: Annotated[
        list[int] | None,
        Field(
            description="Grid sizes in code points. Defaults to the server's configured grid."
        ),
    ] = None
    tokenizer: Annotated[
        str | None,
        Field(
            description='Token counter id (e.g. `tiktoken:o200k_base`). Force-materialized at creation.'
        ),
    ] = None
    embedder_provider: Annotated[
        str | None,
        Field(
            description="Embedder provider override; defaults to the server's configured provider."
        ),
    ] = None
    embedder_model: Annotated[
        str | None,
        Field(
            description="Embedder model override; defaults to the server's configured model."
        ),
    ] = None


class SizeCount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    size: int
    count: int


class CorpusList(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    corpora: list[str]


class DocumentMetadataEntry(BaseModel):
    """
    One caller-supplied metadata key/value pair.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    key: str
    value: str


class PutDocumentRequest(BaseModel):
    """
    A document to add or replace.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(description='The full document text. Never normalized.')]
    metadata: Annotated[
        list[DocumentMetadataEntry] | None,
        Field(
            description='Caller-supplied metadata, preserved as an ordered list of pairs.'
        ),
    ] = None


class BatchDocumentItem(BaseModel):
    """
    One document in a batch, keyed by its id.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: Annotated[str, Field(max_length=512, min_length=1)]
    text: str
    metadata: list[DocumentMetadataEntry] | None = None


class BatchDocumentsRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    documents: Annotated[list[BatchDocumentItem], Field(min_length=1)]


class DocumentRecord(BaseModel):
    """
    The registry entry for one ingested document.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: str
    codepoint_length: int
    byte_length: int
    slice_count: int
    content_marker: Annotated[
        str, Field(description='SHA-256 (64 lowercase hex) of the full document text.')
    ]
    metadata: list[DocumentMetadataEntry] | None = None


class DocumentPage(BaseModel):
    """
    One page of a cursor-paginated document listing.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    records: list[DocumentRecord]
    next_cursor: Annotated[
        str | None,
        Field(
            description='Opaque cursor for the next page; null when the listing is complete.'
        ),
    ] = None


class Expansion(StrEnum):
    """
    Trade-up mode.
    """

    fill = 'fill'
    retrieved_only = 'retrieved_only'
    off = 'off'


class QueryRequest(BaseModel):
    """
    A retrieval-and-right-size request.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    query: Annotated[
        str,
        Field(description='The natural-language query, embedded once.', min_length=1),
    ]
    token_budget: Annotated[
        int | None,
        Field(
            description="Token budget for the returned context. Omitted or null means dedup only (no trade-up). Capped by the server's maximum budget.",
            ge=0,
        ),
    ] = None
    top_k_per_size: Annotated[
        int | None,
        Field(description='Top-k retrieved per grid size before fusion.', ge=1),
    ] = 10
    strategy: Annotated[str | None, Field(description='Selection strategy name.')] = (
        'greedy_upward'
    )
    expansion: Annotated[Expansion | None, Field(description='Trade-up mode.')] = 'fill'
    sizes: Annotated[
        list[int] | None,
        Field(
            description='Restrict the fan-out to these grid sizes; defaults to all sizes.'
        ),
    ] = None
    tokenizer: Annotated[
        str | None,
        Field(
            description='Override the corpus tokenizer for this request (counts recomputed on the fly).'
        ),
    ] = None
    max_slice_size: Annotated[
        int | None, Field(description='Cap on how large a traded-up slice may grow.')
    ] = None
    include_text: Annotated[
        bool | None, Field(description='Include slice text in results.')
    ] = True
    include_trace: Annotated[
        bool | None, Field(description='Include the full substitution trace.')
    ] = True


class BudgetReport(BaseModel):
    """
    Budget arithmetic for the selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    limit: Annotated[
        int | None,
        Field(
            description='The effective budget cap; null when unbounded (dedup only).'
        ),
    ] = None
    used: Annotated[int, Field(description='Tokens the selection consumed.')]
    counter: Annotated[
        str, Field(description='The token counter id under which usage was measured.')
    ]


class FanoutStatus(BaseModel):
    """
    Whether one size fan-out succeeded.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    size: int
    ok: bool
    hits: Annotated[
        int | None,
        Field(description='Number of hits returned by this size (0 when it failed).'),
    ] = None
    error: Annotated[
        str | None, Field(description='Failure reason when this size did not answer.')
    ] = None


class SliceCoords(BaseModel):
    """
    The identity and geometry of one slice.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: str
    size: int
    codepoint_offset: int
    codepoint_length: int
    codepoint_end: int
    own_marker: Annotated[
        str, Field(description="SHA-256 (64 lowercase hex) of the slice's UTF-8 bytes.")
    ]


class RetrievalInfo(BaseModel):
    """
    How a slice was retrieved. Score is null for a traded-up slice — never fabricated.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    retrieved: Annotated[
        bool,
        Field(description='True when this exact slice was itself a retrieval hit.'),
    ]
    rank_in_size: Annotated[
        int | None,
        Field(description='0-based rank within its size, or null if not retrieved.'),
    ] = None
    score: Annotated[
        float | None,
        Field(description='Raw store score (ordinal within one size only), or null.'),
    ] = None


class Action(StrEnum):
    kept = 'kept'
    traded_up = 'traded_up'


class SelectionInfo(BaseModel):
    """
    What the selection engine did with this slice.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    action: Action
    replaced: Annotated[
        list[str], Field(description='Ids of slices this one replaced or subsumed.')
    ]
    levels: Annotated[
        int, Field(description='How many grid levels this slice was traded up.')
    ]


class EvidenceItem(BaseModel):
    """
    A genuine retrieval that supports a selected slice.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    size: int
    codepoint_offset: int
    score: Annotated[
        float | None, Field(description='Raw within-size score of this supporting hit.')
    ] = None
    rank_in_size: int | None = None
    fused_rank: int


class Provenance(StrEnum):
    retrieved = 'retrieved'
    traded_up = 'traded_up'


class QueryResult(BaseModel):
    """
    One slice in the right-sized selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description="The slice's deterministic id.")]
    coords: SliceCoords
    text: Annotated[
        str | None,
        Field(description='The slice text; null when text was not requested.'),
    ] = None
    token_count: int | None
    provenance: Provenance
    effective_rank: Annotated[
        int, Field(description="Best fused rank across this slice's evidence.")
    ]
    contiguous_with_next: Annotated[
        bool,
        Field(
            description='True when the next result immediately follows this slice in the same document.'
        ),
    ]
    retrieval: RetrievalInfo
    selection: SelectionInfo
    evidence: list[EvidenceItem]


class FusionTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sizes: list[int]
    candidate_count: int


class ForestTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hit_count: int
    edge_count: int
    anomaly_count: int
    participation_rate: float
    max_depth: int


class DedupEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kept_id: str
    dropped_ids: list[str]


class SkippedUnaffordable(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    tokens: int
    budget_left: int


class InitialPackTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    selected_ids: list[str]
    skipped_unaffordable: list[SkippedUnaffordable]
    smallest_unaffordable_tokens: int | None = None


class ToProvenance(StrEnum):
    retrieved = 'retrieved'
    fetched = 'fetched'


class TradeUpEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    round: int
    from_id: str
    to_id: str
    to_provenance: ToProvenance
    subsumed_ids: list[str]
    delta_tokens: int
    budget_left: int


class Reason(StrEnum):
    over_budget = 'over_budget'
    stale_parent = 'stale_parent'
    fetch_miss = 'fetch_miss'
    saturated = 'saturated'


class RejectionEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    round: int
    target_id: str
    reason: Reason
    delta_tokens: int | None = None


class FinalTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokens_used: int
    budget: int | None = None
    utilization: float | None = None
    budget_exhausted: bool


class ErrorDetail(BaseModel):
    """
    The error payload inside the envelope.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(description='Stable machine-readable error code.')]
    message: str
    details: dict[str, Any] | None = None
    request_id: Annotated[
        str | None, Field(description='The request id, echoed for correlation.')
    ] = None


class ErrorEnvelope(BaseModel):
    """
    The uniform error envelope wrapping every non-2xx response.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    error: ErrorDetail


class Corpus(BaseModel):
    """
    A corpus with its frozen configuration and current counts.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    grid: GridSpec
    embedder: Annotated[
        str, Field(description='The pinned embedder fingerprint (`provider:model`).')
    ]
    dimension: Annotated[
        int, Field(description='The embedding dimension probed at creation.')
    ]
    tokenizer: Annotated[str, Field(description='The pinned token counter id.')]
    document_count: int
    points_by_size: Annotated[
        list[SizeCount], Field(description='Per-size point counts, ascending by size.')
    ]
    degraded: Annotated[
        list[str],
        Field(description='Degradation reasons; an empty list means healthy.'),
    ]


class BatchDocumentStatus(BaseModel):
    """
    The outcome for one document in a batch.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    document_id: str
    ok: bool
    record: DocumentRecord | None = None
    error: ErrorDetail | None = None


class BatchDocumentsResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    results: list[BatchDocumentStatus]


class SubstitutionTrace(BaseModel):
    """
    The full lifecycle record of one selection run — the explainability contract.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fusion: FusionTrace
    forest: ForestTrace
    dedup: list[DedupEntry]
    initial_pack: InitialPackTrace
    trade_ups: list[TradeUpEntry]
    rejections: list[RejectionEntry]
    final: FinalTrace
    warnings: list[str] | None = None


class QueryResponse(BaseModel):
    """
    The right-sized selection.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    corpus: str
    strategy: str
    budget: BudgetReport
    partial: Annotated[
        bool,
        Field(
            description='True when at least one size fan-out failed but the query still succeeded.'
        ),
    ]
    fanout: Annotated[
        list[FanoutStatus] | None, Field(description='Per-size fan-out status.')
    ] = None
    results: list[QueryResult]
    trace: SubstitutionTrace | None = None
    warnings: list[str] | None = None
